### ISSUE TITLE
Invalid line

### ISSUE THREAD

**Issue by mr-gilberto** [newscoop/legacy-plugin-accounting#6]
Line 581   /Classes/PHPExcel/Calculation/Functions.php

Have a break without for loop... this line  must be

} elseif(is_array($value)) {
                return 64;
}

intsead of 

} elseif(is_array($value)) {
return 64;
break;
}

**Comment by m038** [comment]
Thanks for your suggestion! Though this code is from an external library, so we don't maintain it. Maybe you can make a PR for the original library at https://github.com/PHPOffice/PHPExcel ?
